from __future__ import annotations

import os
import sqlite3
from contextlib import contextmanager
from typing import Any, Iterator

from config import settings
from security import hash_password

SQLITE_SCHEMA = [
    """
    CREATE TABLE IF NOT EXISTS users (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        username TEXT UNIQUE NOT NULL,
        display_name TEXT NOT NULL,
        password_hash TEXT NOT NULL,
        role TEXT NOT NULL CHECK(role IN ('employee','fleet_admin')),
        active INTEGER NOT NULL DEFAULT 1,
        created_at TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS cars (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        plate_number TEXT UNIQUE NOT NULL,
        model TEXT NOT NULL,
        active INTEGER NOT NULL DEFAULT 1,
        created_at TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS reservations (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        car_id INTEGER NOT NULL REFERENCES cars(id),
        created_by_id INTEGER NOT NULL REFERENCES users(id),
        employee_name TEXT NOT NULL,
        start_time TEXT NOT NULL,
        end_time TEXT NOT NULL,
        purpose TEXT,
        status TEXT NOT NULL DEFAULT 'pending'
            CHECK(status IN ('pending','approved','rejected','cancelled')),
        decision_reason TEXT,
        decided_by_id INTEGER REFERENCES users(id),
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS audit_log (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        reservation_id INTEGER NOT NULL REFERENCES reservations(id),
        actor_id INTEGER NOT NULL REFERENCES users(id),
        action TEXT NOT NULL,
        reason TEXT,
        at TEXT NOT NULL
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_reservations_car_time ON reservations(car_id, start_time, end_time)",
    "CREATE INDEX IF NOT EXISTS idx_reservations_status ON reservations(status)",
    "CREATE INDEX IF NOT EXISTS idx_audit_reservation ON audit_log(reservation_id)",
]

POSTGRES_SCHEMA = [
    """
    CREATE TABLE IF NOT EXISTS users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username TEXT UNIQUE NOT NULL,
        display_name TEXT NOT NULL,
        password_hash TEXT NOT NULL,
        role TEXT NOT NULL CHECK(role IN ('employee','fleet_admin')),
        active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)),
        created_at TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS cars (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        plate_number TEXT UNIQUE NOT NULL,
        model TEXT NOT NULL,
        active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)),
        created_at TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS reservations (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        car_id INTEGER NOT NULL REFERENCES cars(id),
        created_by_id INTEGER NOT NULL REFERENCES users(id),
        employee_name TEXT NOT NULL,
        start_time TEXT NOT NULL,
        end_time TEXT NOT NULL,
        purpose TEXT,
        status TEXT NOT NULL DEFAULT 'pending'
            CHECK(status IN ('pending','approved','rejected','cancelled')),
        decision_reason TEXT,
        decided_by_id INTEGER REFERENCES users(id),
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS audit_log (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        reservation_id INTEGER NOT NULL REFERENCES reservations(id),
        actor_id INTEGER NOT NULL REFERENCES users(id),
        action TEXT NOT NULL,
        reason TEXT,
        at TEXT NOT NULL
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_reservations_car_time ON reservations(car_id, start_time, end_time)",
    "CREATE INDEX IF NOT EXISTS idx_reservations_status ON reservations(status)",
    "CREATE INDEX IF NOT EXISTS idx_audit_reservation ON audit_log(reservation_id)",
]

DEMO_USERS = [
    ("admin", "Fleet Admin", "admin123", "fleet_admin"),
    ("ivan", "Ivan Petrov", "employee123", "employee"),
]


def _db_path() -> str:
    return os.getenv("DB_PATH", settings.db_path)


def _database_url() -> str | None:
    return os.getenv("DATABASE_URL", settings.database_url or "") or None


class QueryResult:
    def __init__(self, cursor: Any, lastrowid: int | None = None):
        self._cursor = cursor
        self.lastrowid = lastrowid

    @property
    def rowcount(self) -> int:
        return self._cursor.rowcount

    def fetchone(self):
        return self._cursor.fetchone()

    def fetchall(self):
        return self._cursor.fetchall()


class SQLiteConnectionAdapter:
    backend = "sqlite"

    def __init__(self, conn: sqlite3.Connection):
        self._conn = conn

    def execute(self, query: str, params: tuple = ()) -> QueryResult:
        cursor = self._conn.execute(query, params)
        return QueryResult(cursor, lastrowid=getattr(cursor, "lastrowid", None))

    def begin(self) -> None:
        self._conn.execute("BEGIN IMMEDIATE")

    def commit(self) -> None:
        self._conn.execute("COMMIT")

    def rollback(self) -> None:
        self._conn.execute("ROLLBACK")

    def close(self) -> None:
        self._conn.close()


class PostgresConnectionAdapter:
    backend = "postgres"

    def __init__(self, conn: Any):
        self._conn = conn

    def execute(self, query: str, params: tuple = ()) -> QueryResult:
        cursor = self._conn.cursor()
        cursor.execute(query.replace("?", "%s"), params)
        return QueryResult(cursor)

    def begin(self) -> None:
        self.execute("BEGIN")

    def commit(self) -> None:
        self._conn.commit()

    def rollback(self) -> None:
        self._conn.rollback()

    def close(self) -> None:
        self._conn.close()


@contextmanager
def get_conn() -> Iterator[SQLiteConnectionAdapter | PostgresConnectionAdapter]:
    database_url = _database_url()
    if database_url:
        try:
            from psycopg import connect
            from psycopg.rows import dict_row
        except ImportError as exc:
            raise RuntimeError("DATABASE_URL is set but psycopg is not installed") from exc

        conn = connect(database_url, autocommit=True, row_factory=dict_row)
        adapter = PostgresConnectionAdapter(conn)
        try:
            yield adapter
        finally:
            adapter.close()
        return

    conn = sqlite3.connect(_db_path(), timeout=30, isolation_level=None)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA foreign_keys=ON")
    adapter = SQLiteConnectionAdapter(conn)
    try:
        yield adapter
    finally:
        adapter.close()


@contextmanager
def transaction(conn: SQLiteConnectionAdapter | PostgresConnectionAdapter) -> Iterator[SQLiteConnectionAdapter | PostgresConnectionAdapter]:
    conn.begin()
    try:
        yield conn
    except Exception:
        conn.rollback()
        raise
    else:
        conn.commit()


def init_db() -> None:
    if settings.db_backend == "sqlite":
        db_path = _db_path()
        directory = os.path.dirname(db_path)
        if directory:
            os.makedirs(directory, exist_ok=True)

    with get_conn() as conn:
        schema = POSTGRES_SCHEMA if conn.backend == "postgres" else SQLITE_SCHEMA
        for stmt in schema:
            conn.execute(stmt)
        if settings.app_env == "dev":
            _seed_users(conn)


def _seed_users(conn: SQLiteConnectionAdapter | PostgresConnectionAdapter) -> None:
    from datetime import datetime, timezone

    now = datetime.now(timezone.utc).isoformat()
    for username, display, password, role in DEMO_USERS:
        exists = conn.execute("SELECT 1 FROM users WHERE username=?", (username,)).fetchone()
        if exists:
            continue
        conn.execute(
            """
            INSERT INTO users(username, display_name, password_hash, role, created_at)
            VALUES(?, ?, ?, ?, ?)
            """,
            (username, display, hash_password(password), role, now),
        )
