from __future__ import annotations

import os
import sqlite3
from contextlib import contextmanager
from typing import Any, Iterator

from config import settings

SQLITE_SCHEMA = [
    """
    CREATE TABLE IF NOT EXISTS users (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        username TEXT UNIQUE NOT NULL,
        display_name TEXT NOT NULL,
        password_hash TEXT NOT NULL,
        role TEXT NOT NULL CHECK(role IN ('employee','fleet_admin')),
        active INTEGER NOT NULL DEFAULT 1,
        created_at TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS cars (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        plate_number TEXT UNIQUE NOT NULL,
        model TEXT NOT NULL,
        active INTEGER NOT NULL DEFAULT 1,
        created_at TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS reservations (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        car_id INTEGER NOT NULL REFERENCES cars(id),
        created_by_id INTEGER NOT NULL REFERENCES users(id),
        employee_name TEXT NOT NULL,
        start_time TEXT NOT NULL,
        end_time TEXT NOT NULL,
        purpose TEXT,
        status TEXT NOT NULL DEFAULT 'pending'
            CHECK(status IN ('pending','approved','rejected','cancelled')),
        checked_out_at TEXT,
        returned_at TEXT,
        decision_reason TEXT,
        decided_by_id INTEGER REFERENCES users(id),
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS audit_log (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        reservation_id INTEGER NOT NULL REFERENCES reservations(id),
        actor_id INTEGER NOT NULL REFERENCES users(id),
        action TEXT NOT NULL,
        reason TEXT,
        at TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS notifications (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        user_id INTEGER NOT NULL REFERENCES users(id),
        kind TEXT NOT NULL,
        title TEXT NOT NULL,
        body TEXT NOT NULL,
        reservation_id INTEGER REFERENCES reservations(id),
        read_at TEXT,
        created_at TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS notification_deliveries (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        notification_id INTEGER NOT NULL REFERENCES notifications(id),
        channel TEXT NOT NULL,
        status TEXT NOT NULL,
        detail TEXT,
        delivered_at TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS user_audit_log (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        actor_id INTEGER NOT NULL REFERENCES users(id),
        target_user_id INTEGER NOT NULL REFERENCES users(id),
        action TEXT NOT NULL,
        reason TEXT,
        at TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS car_blackouts (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        car_id INTEGER NOT NULL REFERENCES cars(id),
        kind TEXT NOT NULL CHECK(kind IN ('service','maintenance','inspection','blocked')),
        start_time TEXT NOT NULL,
        end_time TEXT NOT NULL,
        reason TEXT,
        active INTEGER NOT NULL DEFAULT 1,
        created_by_id INTEGER NOT NULL REFERENCES users(id),
        created_at TEXT NOT NULL
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_reservations_car_time ON reservations(car_id, start_time, end_time)",
    "CREATE INDEX IF NOT EXISTS idx_reservations_status ON reservations(status)",
    "CREATE INDEX IF NOT EXISTS idx_audit_reservation ON audit_log(reservation_id)",
    "CREATE INDEX IF NOT EXISTS idx_notifications_user_created ON notifications(user_id, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_notifications_user_read ON notifications(user_id, read_at)",
    "CREATE INDEX IF NOT EXISTS idx_notification_deliveries_notification ON notification_deliveries(notification_id, delivered_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_user_audit_target ON user_audit_log(target_user_id, at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_blackouts_car_time ON car_blackouts(car_id, start_time, end_time)",
]

POSTGRES_SCHEMA = [
    """
    CREATE TABLE IF NOT EXISTS users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username TEXT UNIQUE NOT NULL,
        display_name TEXT NOT NULL,
        password_hash TEXT NOT NULL,
        role TEXT NOT NULL CHECK(role IN ('employee','fleet_admin')),
        active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)),
        created_at TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS cars (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        plate_number TEXT UNIQUE NOT NULL,
        model TEXT NOT NULL,
        active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)),
        created_at TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS reservations (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        car_id INTEGER NOT NULL REFERENCES cars(id),
        created_by_id INTEGER NOT NULL REFERENCES users(id),
        employee_name TEXT NOT NULL,
        start_time TEXT NOT NULL,
        end_time TEXT NOT NULL,
        purpose TEXT,
        status TEXT NOT NULL DEFAULT 'pending'
            CHECK(status IN ('pending','approved','rejected','cancelled')),
        checked_out_at TEXT,
        returned_at TEXT,
        decision_reason TEXT,
        decided_by_id INTEGER REFERENCES users(id),
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS audit_log (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        reservation_id INTEGER NOT NULL REFERENCES reservations(id),
        actor_id INTEGER NOT NULL REFERENCES users(id),
        action TEXT NOT NULL,
        reason TEXT,
        at TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS notifications (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES users(id),
        kind TEXT NOT NULL,
        title TEXT NOT NULL,
        body TEXT NOT NULL,
        reservation_id INTEGER REFERENCES reservations(id),
        read_at TEXT,
        created_at TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS notification_deliveries (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        notification_id INTEGER NOT NULL REFERENCES notifications(id),
        channel TEXT NOT NULL,
        status TEXT NOT NULL,
        detail TEXT,
        delivered_at TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS user_audit_log (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        actor_id INTEGER NOT NULL REFERENCES users(id),
        target_user_id INTEGER NOT NULL REFERENCES users(id),
        action TEXT NOT NULL,
        reason TEXT,
        at TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS car_blackouts (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        car_id INTEGER NOT NULL REFERENCES cars(id),
        kind TEXT NOT NULL CHECK(kind IN ('service','maintenance','inspection','blocked')),
        start_time TEXT NOT NULL,
        end_time TEXT NOT NULL,
        reason TEXT,
        active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)),
        created_by_id INTEGER NOT NULL REFERENCES users(id),
        created_at TEXT NOT NULL
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_reservations_car_time ON reservations(car_id, start_time, end_time)",
    "CREATE INDEX IF NOT EXISTS idx_reservations_status ON reservations(status)",
    "CREATE INDEX IF NOT EXISTS idx_audit_reservation ON audit_log(reservation_id)",
    "CREATE INDEX IF NOT EXISTS idx_notifications_user_created ON notifications(user_id, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_notifications_user_read ON notifications(user_id, read_at)",
    "CREATE INDEX IF NOT EXISTS idx_notification_deliveries_notification ON notification_deliveries(notification_id, delivered_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_user_audit_target ON user_audit_log(target_user_id, at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_blackouts_car_time ON car_blackouts(car_id, start_time, end_time)",
]


def _db_path() -> str:
    return os.getenv("DB_PATH", settings.db_path)


def _database_url() -> str | None:
    return os.getenv("DATABASE_URL", settings.database_url or "") or None


class QueryResult:
    def __init__(self, cursor: Any, lastrowid: int | None = None):
        self._cursor = cursor
        self.lastrowid = lastrowid

    @property
    def rowcount(self) -> int:
        return self._cursor.rowcount

    def fetchone(self):
        return self._cursor.fetchone()

    def fetchall(self):
        return self._cursor.fetchall()


class SQLiteConnectionAdapter:
    backend = "sqlite"

    def __init__(self, conn: sqlite3.Connection):
        self._conn = conn

    def execute(self, query: str, params: tuple = ()) -> QueryResult:
        cursor = self._conn.execute(query, params)
        return QueryResult(cursor, lastrowid=getattr(cursor, "lastrowid", None))

    def begin(self) -> None:
        self._conn.execute("BEGIN IMMEDIATE")

    def commit(self) -> None:
        self._conn.execute("COMMIT")

    def rollback(self) -> None:
        self._conn.execute("ROLLBACK")

    def close(self) -> None:
        self._conn.close()


class PostgresConnectionAdapter:
    backend = "postgres"

    def __init__(self, conn: Any):
        self._conn = conn

    def execute(self, query: str, params: tuple = ()) -> QueryResult:
        cursor = self._conn.cursor()
        cursor.execute(query.replace("?", "%s"), params)
        return QueryResult(cursor)

    def begin(self) -> None:
        self.execute("BEGIN")

    def commit(self) -> None:
        self._conn.commit()

    def rollback(self) -> None:
        self._conn.rollback()

    def close(self) -> None:
        self._conn.close()


@contextmanager
def get_conn() -> Iterator[SQLiteConnectionAdapter | PostgresConnectionAdapter]:
    database_url = _database_url()
    if database_url:
        try:
            from psycopg import connect
            from psycopg.rows import dict_row
        except ImportError as exc:
            raise RuntimeError("DATABASE_URL is set but psycopg is not installed") from exc

        conn = connect(database_url, autocommit=True, row_factory=dict_row)
        adapter = PostgresConnectionAdapter(conn)
        try:
            yield adapter
        finally:
            adapter.close()
        return

    conn = sqlite3.connect(_db_path(), timeout=30, isolation_level=None)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA foreign_keys=ON")
    adapter = SQLiteConnectionAdapter(conn)
    try:
        yield adapter
    finally:
        adapter.close()


@contextmanager
def transaction(conn: SQLiteConnectionAdapter | PostgresConnectionAdapter) -> Iterator[SQLiteConnectionAdapter | PostgresConnectionAdapter]:
    conn.begin()
    try:
        yield conn
    except Exception:
        conn.rollback()
        raise
    else:
        conn.commit()


def _table_columns(conn: SQLiteConnectionAdapter | PostgresConnectionAdapter, table_name: str) -> set[str]:
    if conn.backend == "postgres":
        rows = conn.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_schema = current_schema() AND table_name = ?
            """,
            (table_name,),
        ).fetchall()
        return {str(row["column_name"]) for row in rows}

    rows = conn.execute(f"PRAGMA table_info({table_name})").fetchall()
    return {str(row["name"]) for row in rows}


def _ensure_column(
    conn: SQLiteConnectionAdapter | PostgresConnectionAdapter,
    table_name: str,
    column_name: str,
    column_type: str,
) -> None:
    if column_name in _table_columns(conn, table_name):
        return
    conn.execute(f"ALTER TABLE {table_name} ADD COLUMN {column_name} {column_type}")


def _apply_runtime_upgrades(conn: SQLiteConnectionAdapter | PostgresConnectionAdapter) -> None:
    _ensure_column(conn, "reservations", "checked_out_at", "TEXT")
    _ensure_column(conn, "reservations", "returned_at", "TEXT")


def init_db() -> None:
    if settings.db_backend == "sqlite":
        db_path = _db_path()
        directory = os.path.dirname(db_path)
        if directory:
            os.makedirs(directory, exist_ok=True)

    with get_conn() as conn:
        schema = POSTGRES_SCHEMA if conn.backend == "postgres" else SQLITE_SCHEMA
        for stmt in schema:
            conn.execute(stmt)
        _apply_runtime_upgrades(conn)
